name: fymoney
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  floor: ^1.5.0
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  connectivity_plus: ^4.0.1
  flutter_screenutil: ^5.9.0
  syncfusion_localizations: ^25.2.4
  syncfusion_flutter_calendar: ^25.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/vector/
    - assets/raster/
    - assets/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: Kodchasan
      fonts:
        - asset: assets/fonts/kodchasan.ttf

flutter_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: "assets/logo.jpg"